.PHONY: clean All

All:
	@echo "----------Building project:[ EPI - Debug ]----------"
	@"$(MAKE)" -f  "EPI.mk"
clean:
	@echo "----------Cleaning project:[ EPI - Debug ]----------"
	@"$(MAKE)" -f  "EPI.mk" clean
