.PHONY: clean All

All:
	@echo "----------Building project:[ Chapter7 - Debug ]----------"
	@cd "Chapter7" && "$(MAKE)" -f  "Chapter7.mk"
clean:
	@echo "----------Cleaning project:[ Chapter7 - Debug ]----------"
	@cd "Chapter7" && "$(MAKE)" -f  "Chapter7.mk" clean
